# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SMS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SMS

pod 'RxSwift'
pod 'RxAlamofire'
pod 'Kingfisher'
pod 'FSCalendar'
pod 'RxCocoa'
pod 'RxOptional'
pod 'RxFlow'
pod 'LayoutHelper'
pod 'RNCryptor', '~> 5.0'
pod 'JTAppleCalendar'
pod 'SkyFloatingLabelTextField'

end
