# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "SMS.xcodeproj")
    build_app(workspace: "SMS.xcworkspace", scheme: "SMS")
    upload_to_app_store
  end

 desc "Webhook which App Upload Success"
 lane :send_slack do |options|
    slack(
      message: "앱이 App Store Connect에 성공적으로 업로드 되었습니다.",
      channel: "#이현욱[iOS]",
      payload: {
        "Version": options[:version]
      }
    )
  end

  desc "Make ipa file"
  lane :makeipa do
    increment_build_number(xcodeproj: "SMS.xcodeproj")
    gym
   end
	
  desc "Test App"
  lane :tests do
    scan
   end
end
