name: CI

on:
  push:
    branches: [ Develop ]
  pull_request:
    branches: [ Develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: CI Start
      run: echo CI Start!
      
    - name: Cocoapods
      run: pod install
      
    - name: Build and Test
      run: xcodebuild test -workspace SMS.xcworkspace -scheme 'SMSTests' -destination 'platform=iOS Simulator,name=iPhone 8' test | xcpretty --test --color
   
